In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.datasets import load_boston
import tensorflow.compat.v1 as tf

In [4]:
#create tensorflow object
hello_constant =  tf.constant('hello world')

In [5]:
hello_constant

<tf.Tensor: id=0, shape=(), dtype=string, numpy=b'hello world'>

# Tensorflow Session()

In [14]:
with tf.Session() as sess:
    hello_constant =  tf.constant('hello world')
    # Run the tf.constant operation in the session
    output = sess.run(hello_constant) #.decode()
    print(output)

b'hello world'


### Three type of data
##### > constant
#### > placeholder
#### > variable

In [7]:
#import tf
import tensorflow.compat.v1 as tf

In [8]:
# check version of tensorflow
print(tf.__version__)

2.0.0


l'unite central de donnee en tensorflow est un un 'tensor'. A tensor consiste a un enssemble de valeur forme en tableau ou array de n'importe quel nombre de dimension. un Rank est son nombre de dimension. Ici Nous avons quelques examples de tensors:

> 3                         # un tensor de rank 0, ceci est un scalaire de forne [] <br>
> [1, 2, 3]                 # un tensor de rank 1, ceeci est un vecteur de forme [3]<br>
> [[1,2,3], [4,5,6]]        # un tensor de rank 2 , ceci est une matrice [2,3]<br>
> [[[1,2,3]], [[7, 8, 9]]] # un tensor de rank 3 et pour forme [2, 1, 3]<br>

In [9]:
# initialiser une constante 
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(3.0) # aussi tf.float32 implicit
print(node1, node2)

tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(3.0, shape=(), dtype=float32)


In [15]:
#TF 2.0 supports eager execution which means you don't have to explicitly create a session and run the code in it.
#So the simplest solution would be:
sess = tf.Session()
print(sess.run([node1, node2]))
sess.close()

tf.Tensor(3.0, shape=(), dtype=float32) tf.Tensor(3.0, shape=(), dtype=float32)


AttributeError: Tensor.graph is meaningless when eager execution is enabled.

##### simple operation sur les tf.constant

In [19]:
a = tf.constant(0.5)
b = tf.constant(6.0)
c = a * b
print(c)

tf.Tensor(3.0, shape=(), dtype=float32)


# Tensorflow placeholders
### > Un "placeholder" est une promesse de fournir une valeur  plustard

In [20]:
import tensorflow as tf
# a = tf.placeholder(tf.float32)
# b = tf.placeholder(tf.float32)

# adder_node = a + b
# seess = tf.Session()
# print(seess.run(adder_node, feed_dict={a:[1, 2, 3], b:[4, 5, 6]}))

a = [1,2,3]
b = [4,5,6]
adder_node = a + b
print(adder_node)

[1, 2, 3, 4, 5, 6]


In [22]:
#Do another calculation
Mult_5 = adder_node * 5
print(Mult_5)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


# Tensorflow Variable

#### les variables tensorflow nous permettent des parametres d'apprentissage a notre graphe
#### y = .2 + .3*X

In [25]:
import tensorflow as tf
W1 = tf.Variable([.5], tf.float32)
#init = tf.global_variables_initializer()
#sess.run(init)
print(W1)

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.5], dtype=float32)>


In [28]:
# faire un model lineaire
a = tf.Variable([-3])
b = tf.Variable([2])
x = tf.Variable([1,2,3,4,5,6,7])
model_lineaire = a + b*x
model_lineaire

<tf.Tensor: id=94, shape=(7,), dtype=int32, numpy=array([-1,  1,  3,  5,  7,  9, 11], dtype=int32)>

### Tensorflow math

In [35]:
tf.add(5.0, 10.0)

<tf.Tensor: id=107, shape=(), dtype=float32, numpy=15.0>

In [36]:
tf.subtract(10, 4)

<tf.Tensor: id=110, shape=(), dtype=int32, numpy=6>

In [37]:
tf.multiply(2, 20)

<tf.Tensor: id=113, shape=(), dtype=int32, numpy=40>

### Converting Data Types

In [42]:
tf.add(tf.constant(4.0), tf.constant(2)) #echec avec ValueError: ceci a besoin d'un meilleure typage

InvalidArgumentError: cannot compute Add as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:Add]

In [48]:
tf.add(tf.cast(tf.constant(4.0), tf.int32), tf.constant(2)) # probleme regle

<tf.Tensor: id=139, shape=(), dtype=int32, numpy=6>

In [57]:
# pour la division
x = tf.constant(40)
y = tf.constant(5)
z = tf.subtract(tf.cast(tf.divide(x, y), tf.int32), tf.constant(1))
print(z)

tf.Tensor(7, shape=(), dtype=int32)


# Session 1 :  complet , Ceux que nous avons apris
###### > c'est quoi le DeepLearning
###### > installer tensorflow
###### > importer tensorflow 
###### > les <s>sessions</s>  n'existe plus
###### > constante , variable ,  <s>placeholder</s> n'existe plus
###### > operation avec tensor 
###### > les types et conversion de types

# Activations function

### Sigmoid ou regression Logistic

In [4]:
#f(x)  = 1 / (1-exp(-bX))
import numpy as np

def sigmoid_(x):
    return 1 / (1+np.exp(-x))

a = [1,2,0.5,0,-1,-.90]
for i in a:
    print(sigmoid_(i))

0.7310585786300049
0.8807970779778823
0.6224593312018546
0.5
0.2689414213699951
0.289050497374996


### Tanh ou fonction hyperbolique

In [5]:
def tanh_(a):
    return np.tanh(a)

a = [-2,-3,-4,0,2,3,4]
for i in a:
    print(tanh_(i))

-0.9640275800758169
-0.9950547536867305
-0.999329299739067
0.0
0.9640275800758169
0.9950547536867305
0.999329299739067


### Relu ou maximum

In [7]:
def relu_(a):
    return np.maximum(0, a)

a = [-2,-3,-4,0,2,3,4]
for i in a:
    print(relu_(i))

0
0
0
0
2
3
4


### softmax

In [18]:
scores=[12, 8, .3]
def softmax_(x):
    return np.exp(x) / np.sum(np.exp(x), axis=0)
print(softmax_(scores))
print(sum(softmax_(scores)))

[9.82005792e-01 1.79860635e-02 8.14457845e-06]
1.0


### tf implementation of activations functions

In [2]:
import numpy as np
import tensorflow as tf

a = [-2,1,0,3,2]
# relu activation
relu_activation = tf.nn.relu(a)
# sgmoid activation
sigmoid_activation = tf.sigmoid(tf.cast(a, tf.float32)) #sans cast il yaura un bug "cannot find device .. node"
# 
tanh_activation = tf.tanh(tf.cast(a, tf.float32))

print(relu_activation)
print(sigmoid_activation)
print(tanh_activation)

tf.Tensor([0 1 0 3 2], shape=(5,), dtype=int32)
tf.Tensor([0.11920291 0.7310586  0.5        0.95257413 0.880797  ], shape=(5,), dtype=float32)
tf.Tensor([-0.9640276  0.7615942  0.         0.9950547  0.9640276], shape=(5,), dtype=float32)


In [5]:
# donnees aleatoire tf
a = tf.random.truncated_normal([2,3]) #genere sous distribution normale
print(a)

tf.Tensor(
[[-0.627807   -0.08216891 -0.14454864]
 [-0.6852508  -1.6045313   0.08050168]], shape=(2, 3), dtype=float32)


# fonction de perte
- Une fonction de perte mesure l'écart du modèle actuel par rapport aux données fournies

In [9]:
import tensorflow as tf

#loss function ou fonction de perte
W = tf.Variable([.3], tf.float32)
b = tf.Variable([-.3], tf.float32)
x = [1,2,3,4]
y = [0,-1,-2,-3]

linear_model = W*x +b

squared_delta = tf.square(linear_model - y) #somme(actuel - predit)^2
loss = tf.reduce_sum(squared_delta)
print(squared_delta, loss)

# nous avons aussi the cross entropy that is used for classification model

tf.Tensor([ 0.         1.6899998  6.7599993 15.210001 ], shape=(4,), dtype=float32) tf.Tensor(23.66, shape=(), dtype=float32)


# Model Optimizer
- L’optimiseur modifie chaque variable en fonction de l’importance de la différence de perte par rapport à la variable.

In [27]:
#model optimizer 
# loss function
W = tf.Variable([.5], tf.float32)
b = tf.Variable([.1], tf.float32)
x = [1,2,3,4]
y = [0,-1,-2,-3]
var_list_ = []

linear_model = W*x + b

squared_error = tf.square(linear_model - y)
loss = tf.reduce_sum(squared_error)

optimizer = tf.optimizers.SGD(0.01)
#tf.optimizers.SGD (learning_rate=0.001, lr_decay=0.0, decay_step=100, staircase=False, use_locking=False, name='SGD')
train = optimizer.minimize(loss, var_list_)

for i in range(3):
    train

print([W, b])

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable